# Versioning System For SOAP
# SOAP RELEASE VERSION
SOAP_VERSION_MAJOR = 1
SOAP_VERSION_MINOR = 0
SOAP_VERSION_MAINTENANCE =

VERSION := $(SOAP_VERSION_MAJOR).$(SOAP_VERSION_MINOR)$(SOAP_VERSION_MAINTENANCE)

# Set SOAP_BUILDTYPE
ifdef SOAP_NIGHTLY
    SOAP_BUILDTYPE := NIGHTLY
endif
ifdef SOAP_EXPERIMENTAL
    SOAP_BUILDTYPE := EXPERIMENTAL
endif
ifdef SOAP_MAINTENANCE 
    SOAP_BUILDTYPE := MAINTENANCE 
endif
# Set Unofficial if no buildtype set (Buildtype should ONLY be set by SOAP Devs!)
ifdef SOAP_BUILDTYPE
else
    BLISS_BUILDTYPE := UNOFFICIAL
    BLISS_VERSION_MAJOR := 1
    BLISS_VERSION_MINOR := 0
endif

# Set SOAP version
ifdef SOAP_RELEASE
   SOAP_VERSION := SOAP-v$(VERSION)
else
    SOAP_VERSION := SOAP-v$(VERSION)-$(SOAP_BUILD)-$(SOAP_BUILDTYPE)-$(shell date +%Y%m%d-%H%M)
endif

SOAP_DISPLAY_VERSION := $(VERSION)
SOAP_DISPLAY_BUILDTYPE := $(SOAP_BUILDTYPE)

PRODUCT_PROPERTY_OVERRIDES += \
  ro.soap.version=$(SOAP_DISPLAY_VERSION)
